server:
  port: 8090

spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://config-server:8888"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Exponer el endpoint de Prometheus
  cloud:
    gateway:
      discovery:
        locator:
          # ⬇️ NUEVO: Permite que los headers de autorización se pasen a los microservicios
          allowed-headers:
            - Authorization
          enabled: true # Habilita el enrutamiento automático basado en el serviceId de Eureka
          lower-case-service-id: true # Convierte los serviceId a minúsculas
      routes:
        - id: mcs-customers-route
          # uri 'lb://' indica que se usará el balanceador de carga de Spring Cloud (integrado con Eureka)
          # para encontrar una instancia del servicio 'mcs-customers'.
          uri: lb://mcs-customers
          predicates:
            # Esta ruta se activa si la petición empieza con /api/customers
            - Path=/api/customers, /api/customers/**
          filters:
             # Reescribe la ruta: /api/customers/1 -> /customers/1
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: mcs-orders-route
          uri: lb://mcs-orders
          predicates:
            # Esta ruta se activa si la petición empieza con /api/orders
            - Path=/api/orders, /api/orders/**
          filters:
            # Reescribe la ruta: /api/orders/1 -> /orders/1
            - RewritePath=/api/(?<segment>.*), /${segment}
      default-filters:
        # Elimina el prefijo del serviceId (ej: /mcs-customers) de la ruta.
        # Esto es necesario cuando se usa discovery.locator y rutas manuales.
        - StripPrefix=1
