global:
  scrape_interval: 15s # Frecuencia con la que se recolectan métricas.

scrape_configs:
  - job_name: 'spring-micrometer'
    # No definimos un metrics_path global, lo haremos por target.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __metrics_path__
        regex: (.+):8080 # Si el puerto es 8080 (mcs-customers)
        replacement: /mcs-customers/actuator/prometheus # Usa esta ruta
      - source_labels: [__address__]
        target_label: __metrics_path__
        regex: (.+):8081 # Si el puerto es 8081 (mcs-orders)
        replacement: /mcs-orders/actuator/prometheus # Usa esta ruta
      - source_labels: [__address__]
        target_label: __metrics_path__
        regex: (gateway-server|eureka-server)(.+)? # Para los demás
        replacement: /actuator/prometheus # Usa la ruta por defecto
    
    static_configs:
      - targets:
          - 'mcs-customers:8080'
          - 'mcs-orders:8081'
          - 'gateway-server:8090'
          - 'eureka-server:8761'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']