server:
    port: 8761
spring:
    application:
        name: eureka-server

eureka:
    client:
        # 1. No queremos que el servidor se registre en sí mismo
        register-with-eureka: false
        # 2. No queremos que intente buscar otros servidores
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/