server:
  port: 8081
  servlet:
    context-path: /config-client
spring:  
  application:
    name: config-client
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Valor por defecto: dev
  cloud:
    config:
      uri: http://localhost:8888
spring.config.import: optional:configserver:http://localhost:8888