server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yensei/config-files
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          # Si es local, usa: uri: file:///C:/ruta/a/config-repo
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Exponer el endpoint de Prometheus